//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Signatura_topografica { get; set; }
        public string Isbn { get; set; }
        public string C_Tipo_bibliografia { get; set; }
        public string Autores { get; set; }
        public string editora { get; set; }
        public Nullable<System.DateTime> año_publicacion { get; set; }
        public string ciencia { get; set; }
        public string Idioma { get; set; }
        public string Estado { get; set; }
    }
}
