//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA
{
    using System;
    using System.Collections.Generic;
    
    public partial class usurio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> carnet { get; set; }
        public string tipo_persona { get; set; }
        public string Estado { get; set; }
    }
}
